# Build the container
# docker build --tag wenkokke/manylinux2014_ghc945_i686 --file dockerfiles/Dockerfile.manylinux2014_ghc945_i686 .
FROM quay.io/pypa/manylinux2014_i686

# Link libgmp.so.10 to libgmp.so
RUN ln -s "/usr/lib/libgmp.so.10" "/usr/lib/libgmp.so"

# Install GHC and Cabal
RUN <<EOT bash
set -ex

# Link python3.11 to python3
ln -s "/usr/local/bin/python3.11" "/usr/local/bin/python3"

# Install wget 3.2
python3 -m pip install wget==3.2

# Install GHC 9.4.5
python3 -c "import wget; wget.download('https://downloads.haskell.org/~ghc/9.4.5/ghc-9.4.5-i386-deb9-linux.tar.xz', '/tmp/ghc-9.4.5.tar.xz')"
python3 -c "import shutil; shutil.unpack_archive('/tmp/ghc-9.4.5.tar.xz', '/tmp')"
mv "/tmp/ghc-9.4.5-i386-unknown-linux" "/tmp/ghc"
(cd "/tmp/ghc" && ./configure --prefix="/usr/local")
(cd "/tmp/ghc" && make install)
rm -rf "/tmp/ghc" "/tmp/ghc-9.4.5.tar.xz"

# Bootstrap Cabal 3.10.1.0
python3 -c "import wget; wget.download('https://github.com/haskell/cabal/archive/refs/tags/cabal-install-v3.10.1.0.zip', '/tmp/cabal.zip')"
python3 -c "import shutil; shutil.unpack_archive('/tmp/cabal.zip', '/tmp')"
mv "/tmp/cabal-cabal-install-v3.10.1.0" "/tmp/cabal"
sed -ie 's/+ofd-locking/-ofd-locking/' "/tmp/cabal/bootstrap/linux-9.4.5.json"
(cd "/tmp/cabal" && python3 "./bootstrap/bootstrap.py" -d "./bootstrap/linux-9.4.5.json" -w "/usr/local/bin/ghc-9.4.5")
"/tmp/cabal/_build/bin/cabal" v2-update
"/tmp/cabal/_build/bin/cabal" v2-install cabal-install cabal-install --constraint='lukko -ofd-locking' --overwrite-policy=always --install-method=copy --installdir="/usr/local/bin"
rm -rf "/tmp/cabal" "/tmp/cabal.zip"

# Unlink python3.11 from python3
unlink "/usr/local/bin/python3"
EOT
