# Build the container
# docker build --tag wenkokke/manylinux2014_ghc945_i686 --file Dockerfile.manylinux2014_ghc945_i686 .
FROM quay.io/pypa/manylinux2014_i686

# Link libgmp.so.10 to libgmp.so
RUN ln -s "/usr/lib/libgmp.so.10" "/usr/lib/libgmp.so"

# Install GHC and Cabal
RUN <<EOT bash
set -ex

# Link python3.11 to python3
ln -s "/usr/local/bin/python3.11" "/usr/local/bin/python3"

# Install wget 3.2
python3 -m pip install wget==3.2

# Install GHC 9.2.6
python3 -c "import wget; wget.download('https://downloads.haskell.org/~ghc/9.2.6/ghc-9.2.6-i386-deb9-linux.tar.xz', '/tmp/ghc-9.2.6.tar.xz')"
python3 -c "import shutil; shutil.unpack_archive('/tmp/ghc-9.2.6.tar.xz', '/tmp')"
(cd "/tmp/ghc-9.2.6" && ./configure --prefix="/tmp/ghc-toolset-9.2.6/root/usr")
(cd "/tmp/ghc-9.2.6" && make install)
rm -rf "/tmp/ghc-9.2.6" "/tmp/ghc-9.2.6.tar.xz"

# Bootstrap Cabal 3.10.1.0
python3 -c "import wget; wget.download('https://github.com/haskell/cabal/archive/refs/tags/cabal-install-v3.10.1.0.zip', '/tmp/cabal.zip')"
python3 -c "import shutil; shutil.unpack_archive('/tmp/cabal.zip', '/tmp')"
mv "/tmp/cabal-cabal-install-v3.10.1.0" "/tmp/cabal"
sed -ie "s/+ofd-locking/-ofd-locking/" "/tmp/cabal/bootstrap/linux-9.2.6.json"
(cd "/tmp/cabal" && python3 "./bootstrap/bootstrap.py" -d "./bootstrap/linux-9.2.6.json" -w "/tmp/ghc-toolset-9.2.6/root/usr/bin/ghc-9.2.6")
PATH="/tmp/ghc-toolset-9.2.6/root/usr/bin:${PATH}" "/tmp/cabal/_build/bin/cabal" v2-update
PATH="/tmp/ghc-toolset-9.2.6/root/usr/bin:${PATH}" "/tmp/cabal/_build/bin/cabal" v2-install cabal-install --constraint="lukko -ofd-locking" --overwrite-policy=always --install-method=copy --installdir="/tmp/ghc-toolset-9.2.6/root/usr/bin"

# Bootstrap GHC 9.4.5
python3 -c "import wget; wget.download('https://downloads.haskell.org/~ghc/9.4.5/ghc-9.4.5-src.tar.xz', '/tmp/ghc-9.4.5-src.tar.xz')"
python3 -c "import shutil; shutil.unpack_archive('/tmp/ghc-9.4.5-src.tar.xz', '/tmp')"

## Create and apply the fpic-default patch
mkdir "/tmp/ghc-9.4.5-patches"
cat > "/tmp/ghc-9.4.5-patches/fpic-default.patch" <<EOP
Index: ghc-9.4.5/compiler/GHC/Driver/Session.hs
===================================================================
--- ghc-9.4.5.orig/compiler/GHC/Driver/Session.hs
+++ ghc-9.4.5/compiler/GHC/Driver/Session.hs
@@ -3871,6 +3871,7 @@ default_PIC platform =
     -- of that.  Subsequently we expect all code on aarch64/linux (and macOS) to
     -- be built with -fPIC.
     (OSDarwin,  ArchAArch64) -> [Opt_PIC]
+    (OSLinux,   ArchX86_64)  -> [Opt_PIC]
     (OSLinux,   ArchAArch64) -> [Opt_PIC, Opt_ExternalDynamicRefs]
     (OSLinux,   ArchARM {})  -> [Opt_PIC, Opt_ExternalDynamicRefs]
     (OSOpenBSD, ArchX86_64)  -> [Opt_PIC] -- Due to PIE support in
EOP
(cd "/tmp" && patch -p0 < "/tmp/ghc-9.4.5-patches/fpic-default.patch")
rm -rf "/tmp/ghc-9.4.5-patches"

## Create and update mk/build.mk
cp "/tmp/ghc-9.4.5/mk/build.mk.sample" "/tmp/ghc-9.4.5/mk/build.mk"
cat >> "/tmp/ghc-9.4.5/mk/build.mk" <<EOP

GhcLibHcOpts += -fPIC
GhcRtsHcOpts += -fPIC
GhcRtsCcOpts += -fPIC
BuildFlavour = quick
EOP

(cd "/tmp/ghc-9.4.5" && PATH="/tmp/ghc-toolset-9.2.6/root/usr/bin:${PATH}" ./configure GHC="/tmp/ghc-toolset-9.2.6/root/usr/bin/ghc-9.2.6")
(cd "/tmp/ghc-9.4.5" && PATH="/tmp/ghc-toolset-9.2.6/root/usr/bin:${PATH}" hadrian/build install --docs=none -j --prefix="/usr/local")
rm -rf "/tmp/ghc-toolset-9.2.6" "/tmp/ghc-9.4.5" "/tmp/ghc-9.4.5-src.tar.xz"

# Unlink python3.11 from python3
unlink "/usr/local/bin/python3"

# Install Cabal 3.10.1.0
"/tmp/cabal/_build/bin/cabal" v2-install cabal-install --constraint="lukko -ofd-locking" --overwrite-policy=always --install-method=copy --installdir="/usr/local/bin"
rm -rf "/tmp/cabal" "/tmp/cabal.zip"
EOT
