name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:

  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    - cron: "0 0 * * 0"

  workflow_dispatch:

defaults:
  run:
    shell: sh

jobs:
  manylinux_2_28_ghc945_aarch64:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Set up QEMU (linux/aarch64)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: aarch64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.manylinux_2_28_ghc945_aarch64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/manylinux_2_28_ghc945_aarch64:latest

  manylinux2014_ghc945_i686:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Set up QEMU (linux/i686)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: i686

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.manylinux2014_ghc945_i686
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/manylinux2014_ghc945_i686:latest

  manylinux2014_ghc945_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.manylinux2014_ghc945_x86_64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/manylinux2014_ghc945_x86_64:latest

  musllinux_1_1_ghc945_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.musllinux_1_1_ghc945_x86_64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/musllinux_1_1_ghc945_x86_64:latest
