name: manylinux_2_28_ghc944_x86_64

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile.manylinux_2_28_ghc944_x86_64"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "Dockerfile.manylinux_2_28_ghc944_x86_64"
  workflow_dispatch:

defaults:
  run:
    shell: sh

jobs:
  manylinux_2_28_ghc944_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.manylinux_2_28_ghc944_x86_64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/manylinux_2_28_ghc944_x86_64:latest
