name: manylinux_2_28_ghc984_i686

on:
  push:
    branches:
      - main
    paths:
      - "ghc984/Dockerfile.manylinux_2_28_ghc984_i686"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "ghc984/Dockerfile.manylinux_2_28_ghc984_i686"
  workflow_dispatch:

defaults:
  run:
    shell: sh

jobs:
  manylinux_2_28_ghc984_i686:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v5

      - name: Set up QEMU (linux/i686)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "386"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./ghc984/Dockerfile.manylinux_2_28_ghc984_i686
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/manylinux_2_28_ghc984_i686:latest
