name: musllinux_1_1_ghc948_x86_64

on:
  push:
    branches:
      - main
    paths:
      - "ghc948/Dockerfile.musllinux_1_1_ghc948_x86_64"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "ghc948/Dockerfile.musllinux_1_1_ghc948_x86_64"
  workflow_dispatch:

defaults:
  run:
    shell: sh

jobs:
  musllinux_1_1_ghc948_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./ghc948/Dockerfile.musllinux_1_1_ghc948_x86_64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/musllinux_1_1_ghc948_x86_64:latest
